#-----------------------------------------------------------------------------------------------------------------------
# Install Linux elasticsearch packages
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

- name: Download elasticsearch tar package
  get_url:
    url: '{{ elasticsearch_package_url }}'
    dest: '{{ elasticsearch_package }}'
    timeout: '{{ url_timeout }}'
    checksum: 'sha512:{{ elasticsearch_package_url }}.sha512'
  tags: package_elasticsearch
  register: elasticsearch_get_url
  until: elasticsearch_get_url is not failed
  retries: 2
  delay: 30

- name: Install elasticsearch tar package
  unarchive:
    src: '{{ elasticsearch_package }}'
    dest: '{{ elasticsearch_install_dir }}'
    remote_src: True
    list_files: yes
  register: elasticsearch_archive_contents

- name: Rename directory if it does not match base package name
  command:
    mv '{{ elasticsearch_archive_contents.files[0].split('/')[0] }}' '{{ elasticsearch_rootdir | basename }}'
  args:
    chdir: '{{ elasticsearch_install_dir}}'
  when: "'{{ elasticsearch_rootdir | basename }}' not in '{{ elasticsearch_archive_contents.files[0].split('/')[0] }}'"
