ossGrp1="console
         getting_started
         context
         discover
         home
         management
         status_page
         timelion
         bundles
         saved_objects_management
        "

ossGrp2="visualize
        "

ossGrp3="dashboard
        "

xpackGrp1="advanced_settings
           apm
           canvas
           cross_cluster_replication
           grok_debugger
           index_lifecycle_management
           index_management
           reporting_management
           transform
           machine_learning
           ml
           license_management
          "

xpackGrp2="status_page
           timelion
           upgrade_assistant
           uptime
           visualize
           watcher
           index_patterns
           logstash
           graph
           discover
           dashboard
           dashboard_mode
           canvas
           dev_tools
           infra
          "

xpackGrp3="maps
           lens
          "

xpackGrp4="monitoring
           remote_clusters
           rollup_job
           saved_objects_management
           security
           snapshot_restore
           spaces
           api_keys
          "

xpackExtGrp1="reporting
              api_integration
              alerting_api_integration
              plugin_api_integration
              kerberos_api_integration
             "
xpackExtGrp2="saml_api_integration
              token_api_integration
              oidc_api_integration
              pki_api_integration
              spaces_api_integration
             "
xpackExtGrp3="saved_object_api_integration
              ui_capabilities
              upgrade_assistant_integration
             "
